--!strict

return {
	Enabled = false,
	ActiveSlots = 3,
	Quests = {
		{
			Id = "money_2k",
			Order = 1,
			Type = "total_money_earned",
			Target = 2000,
			Text = "Earn $2K",
			Reward = 1000,
		},
		{
			Id = "play_2m",
			Order = 2,
			Type = "playtime_minutes_total",
			Target = 2,
			Text = "Play for 2 minutes",
			Reward = 2000,
		},
		{
			Id = "brainrots_3",
			Order = 3,
			Type = "brainrots_collected_total",
			Target = 3,
			Text = "Collect 3 brainrots",
			Reward = 3500,
		},
		{
			Id = "money_25k",
			Order = 6,
			Type = "total_money_earned",
			Target = 25000,
			Text = "Earn $25K",
			Reward = 10000,
		},
		{
			Id = "brainrots_8",
			Order = 7,
			Type = "brainrots_collected_total",
			Target = 8,
			Text = "Collect 8 brainrots",
			Reward = 12500,
		},
		{
			Id = "carry_1",
			Order = 8,
			Type = "carry_capacity_upgrade_count",
			Target = 1,
			Text = "Buy 1 carry upgrade",
			Reward = 15000,
		},
		{
			Id = "play_5m",
			Order = 9,
			Type = "playtime_minutes_total",
			Target = 5,
			Text = "Play for 5 minutes",
			Reward = 20000,
		},
		{
			Id = "money_100k",
			Order = 11,
			Type = "total_money_earned",
			Target = 100000,
			Text = "Earn $100K",
			Reward = 40000,
		},
		{
			Id = "rebirth_1",
			Order = 13,
			Type = "rebirth_count",
			Target = 1,
			Text = "Make 1 rebirth",
			Reward = 75000,
		},
		{
			Id = "brainrots_15",
			Order = 14,
			Type = "brainrots_collected_total",
			Target = 15,
			Text = "Collect 15 brainrots",
			Reward = 90000,
		},
		{
			Id = "play_15m",
			Order = 15,
			Type = "playtime_minutes_total",
			Target = 15,
			Text = "Play for 15 minutes",
			Reward = 120000,
		},
		{
			Id = "money_500k",
			Order = 17,
			Type = "total_money_earned",
			Target = 500000,
			Text = "Earn $500K",
			Reward = 250000,
		},
		{
			Id = "rebirth_2",
			Order = 19,
			Type = "rebirth_count",
			Target = 2,
			Text = "Make 2 rebirths",
			Reward = 450000,
		},
		{
			Id = "money_2m",
			Order = 20,
			Type = "total_money_earned",
			Target = 2000000,
			Text = "Earn $2M",
			Reward = 600000,
		},
	},
}
