--!strict

return {
	Enabled = true,
	ActiveSlots = 3,
	Quests = {
		{
			Id = "rebirth_1",
			Order = 1,
			Type = "rebirth_count",
			Target = 1,
			Text = "Make 1 rebirth",
			Reward = 1000,
		},
		{
			Id = "money_5k",
			Order = 2,
			Type = "collect_money_total",
			Target = 5000,
			Text = "Collect $5K",
			Reward = 2000,
		},
		{
			Id = "depth_25",
			Order = 3,
			Type = "reach_depth",
			Target = 2,
			Text = "Reach Depth Level 2",
			Reward = 3500,
		},
		{
			Id = "brainrots_3",
			Order = 4,
			Type = "collect_brainrots_total",
			Target = 3,
			Text = "Collect 3 brainrots",
			Reward = 5000,
		},
		{
			Id = "base_1",
			Order = 5,
			Type = "base_upgrade_count",
			Target = 1,
			Text = "Make 1 base upgrade",
			Reward = 7500,
		},
		{
			Id = "play_3m",
			Order = 6,
			Type = "playtime_minutes_total",
			Target = 3,
			Text = "Play for 3 minutes",
			Reward = 10000,
		},
		{
			Id = "bomb_1",
			Order = 7,
			Type = "bomb_upgrade_count",
			Target = 1,
			Text = "Upgrade bomb 1 time",
			Reward = 12500,
		},
		{
			Id = "speed_1",
			Order = 8,
			Type = "speed_upgrade_count",
			Target = 1,
			Text = "Upgrade player speed 1 time",
			Reward = 15000,
		},
		{
			Id = "carry_1",
			Order = 9,
			Type = "carry_upgrade_count",
			Target = 1,
			Text = "Upgrade carry 1 time",
			Reward = 20000,
		},
		{
			Id = "rebirth_2",
			Order = 10,
			Type = "rebirth_count",
			Target = 2,
			Text = "Make 2 rebirths",
			Reward = 30000,
		},
		{
			Id = "money_50k",
			Order = 11,
			Type = "collect_money_total",
			Target = 50000,
			Text = "Collect $50K",
			Reward = 40000,
		},
		{
			Id = "depth_100",
			Order = 12,
			Type = "reach_depth",
			Target = 3,
			Text = "Reach Depth Level 3",
			Reward = 55000,
		},
		{
			Id = "brainrots_8",
			Order = 13,
			Type = "collect_brainrots_total",
			Target = 8,
			Text = "Collect 8 brainrots",
			Reward = 75000,
		},
		{
			Id = "base_3",
			Order = 14,
			Type = "base_upgrade_count",
			Target = 3,
			Text = "Make 3 base upgrades",
			Reward = 90000,
		},
		{
			Id = "play_10m",
			Order = 15,
			Type = "playtime_minutes_total",
			Target = 10,
			Text = "Play for 10 minutes",
			Reward = 120000,
		},
		{
			Id = "bomb_3",
			Order = 16,
			Type = "bomb_upgrade_count",
			Target = 3,
			Text = "Upgrade bomb 3 times",
			Reward = 180000,
		},
		{
			Id = "speed_3",
			Order = 17,
			Type = "speed_upgrade_count",
			Target = 3,
			Text = "Upgrade player speed 3 times",
			Reward = 250000,
		},
		{
			Id = "carry_2",
			Order = 18,
			Type = "carry_upgrade_count",
			Target = 2,
			Text = "Upgrade carry 2 times",
			Reward = 300000,
		},
		{
			Id = "money_250k",
			Order = 19,
			Type = "collect_money_total",
			Target = 250000,
			Text = "Collect $250K",
			Reward = 450000,
		},
		{
			Id = "depth_250",
			Order = 20,
			Type = "reach_depth",
			Target = 4,
			Text = "Reach Depth Level 4",
			Reward = 600000,
		},
		{
			Id = "brainrots_15",
			Order = 21,
			Type = "collect_brainrots_total",
			Target = 15,
			Text = "Collect 15 brainrots",
			Reward = 800000,
		},
		{
			Id = "base_5",
			Order = 22,
			Type = "base_upgrade_count",
			Target = 5,
			Text = "Make 5 base upgrades",
			Reward = 1000000,
		},
		{
			Id = "play_20m",
			Order = 23,
			Type = "playtime_minutes_total",
			Target = 20,
			Text = "Play for 20 minutes",
			Reward = 1250000,
		},
		{
			Id = "bomb_5",
			Order = 24,
			Type = "bomb_upgrade_count",
			Target = 5,
			Text = "Upgrade bomb 5 times",
			Reward = 1500000,
		},
		{
			Id = "speed_5",
			Order = 25,
			Type = "speed_upgrade_count",
			Target = 5,
			Text = "Upgrade player speed 5 times",
			Reward = 1800000,
		},
		{
			Id = "carry_3",
			Order = 26,
			Type = "carry_upgrade_count",
			Target = 3,
			Text = "Upgrade carry 3 times",
			Reward = 2200000,
		},
	},
}
