--!strict

local TutorialConfiguration = {}

export type TutorialStepDefinition = {
	Text: string,
	TargetType: string,
}

export type TutorialStepPresentation = {
	MaskUi: boolean,
	ShowText: boolean,
	ShowMoney: boolean,
	ShowInventory: boolean,
	ShowBombShopButton: boolean,
	ShowPickaxesFrame: boolean,
	ShowUpgradesFrame: boolean,
	ShowBaseUpgradeSurfaceButton: boolean,
	ShowMobileBombButton: boolean,
	ShowJumpButton: boolean,
	ShowBackButton: boolean,
	BackProxyScale: number,
	UseBlackout: boolean,
}

TutorialConfiguration.FinalStep = 13
TutorialConfiguration.CashGoal = 5
TutorialConfiguration.TutorialCharacterUpgradeId = "Speed1"
TutorialConfiguration.TutorialBaseUpgradeMode = "FirstSlotUnlock"
TutorialConfiguration.LegacyCompletedFinalStep = 9
TutorialConfiguration.BaseUpgradeApproachDistance = 20
TutorialConfiguration.CompletionMessageDuration = 10

local DEFAULT_STEP_PRESENTATION: TutorialStepPresentation = {
	MaskUi = false,
	ShowText = false,
	ShowMoney = false,
	ShowInventory = false,
	ShowBombShopButton = false,
	ShowPickaxesFrame = false,
	ShowUpgradesFrame = false,
	ShowBaseUpgradeSurfaceButton = false,
	ShowMobileBombButton = false,
	ShowJumpButton = false,
	ShowBackButton = false,
	BackProxyScale = 1,
	UseBlackout = false,
}

TutorialConfiguration.Steps = {
	[1] = {
		Text = "Walk to the mining zone",
		TargetType = "WorldMineZone",
	},
	[2] = {
		Text = "Throw a bomb to find Brainrots",
		TargetType = "GuiEquippedBomb",
	},
	[3] = {
		Text = "Pick up the Brainrot",
		TargetType = "WorldBrainrot",
	},
	[4] = {
		Text = "Go to the surface",
		TargetType = "GuiBackButton",
	},
	[5] = {
		Text = "Place Brainrot on your base",
		TargetType = "HybridInventoryOrSlot",
	},
	[6] = {
		Text = "Collect $5 cash",
		TargetType = "WorldCollectCash",
	},
	[7] = {
		Text = "Upgrade your bomb",
		TargetType = "WorldBombShop",
	},
	[8] = {
		Text = "Buy Venom Bomb",
		TargetType = "GuiBuyBombButton",
	},
	[9] = {
		Text = "Upgrade your character",
		TargetType = "WorldCharacterUpgrade",
	},
	[10] = {
		Text = "Well done! Upgrade your character and become faster!",
		TargetType = "GuiCharacterUpgradeButton",
	},
	[11] = {
		Text = "Upgrade your base",
		TargetType = "GuiBaseUpgradeButton",
	},
	[12] = {
		Text = "Well done! Upgrade your base and get more money!",
		TargetType = "None",
	},
	[13] = {
		Text = "Tutorial complete",
		TargetType = "None",
	},
} :: {[number]: TutorialStepDefinition}

TutorialConfiguration.StepPresentations = {
	[1] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = false,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = false,
		ShowJumpButton = false,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[2] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = false,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = true,
		ShowJumpButton = true,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[3] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = false,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = true,
		ShowJumpButton = true,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[4] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = false,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = false,
		ShowJumpButton = false,
		ShowBackButton = true,
		BackProxyScale = 3,
		UseBlackout = false,
	},
	[5] = {
		MaskUi = false,
		ShowText = true,
		ShowMoney = false,
		ShowInventory = true,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = false,
		ShowJumpButton = false,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[6] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = true,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = false,
		ShowJumpButton = false,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[7] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = false,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = false,
		ShowJumpButton = false,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[8] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = true,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = true,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = false,
		ShowJumpButton = false,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[9] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = false,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = false,
		ShowJumpButton = false,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[10] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = false,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = true,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = false,
		ShowJumpButton = false,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[11] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = false,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = true,
		ShowMobileBombButton = false,
		ShowJumpButton = false,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[12] = {
		MaskUi = true,
		ShowText = true,
		ShowMoney = false,
		ShowInventory = false,
		ShowBombShopButton = false,
		ShowPickaxesFrame = false,
		ShowUpgradesFrame = false,
		ShowBaseUpgradeSurfaceButton = false,
		ShowMobileBombButton = false,
		ShowJumpButton = false,
		ShowBackButton = false,
		BackProxyScale = 1,
		UseBlackout = false,
	},
	[13] = DEFAULT_STEP_PRESENTATION,
} :: {[number]: TutorialStepPresentation}

function TutorialConfiguration.GetStepPresentation(step: number): TutorialStepPresentation
	return TutorialConfiguration.StepPresentations[step] or DEFAULT_STEP_PRESENTATION
end

return TutorialConfiguration
