--!strict
-- LOCATION: StarterPlayerScripts/FavoritePromptController
--
-- Experience-like prompts are not available through a built-in Roblox
-- in-experience prompt API. The group-only reward flow is now handled by
-- JoinLikeStandController, so this script intentionally does nothing.
